version: "3.8"

services:
  legacy-landingpage:
    build: .
    container_name: legacy-landingpage
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
